// Compatibility layer. New code should import from lib/auth/index.mjs.
export {
  ALL_DAY_UNLOCK_MINUTES,
  DEFAULT_UNLOCK_MINUTES,
  authPaths,
  authStatus,
  authorize,
  clearUnlockSession,
  createUnlockSession,
  declaredSecrets,
  installAuthToken,
  installLicenseToken,
  licenseSummary,
  localMachineHash,
  maskSecret,
  parseUnlockMinutes,
  resolveSecret,
  supervisorAuthStatus,
  supervisorUnlocked,
  verifyAuthToken,
  verifyLicenseToken,
} from './auth/index.mjs';
